/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package act8_m3;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumne
 */
public class act8 extends javax.swing.JFrame {
    
    String cuadrados[][] = new String[4][4];
    int contador = 0;
    int contadorW = 0;
    int contadorX = 0;

    /**
     * Creates new form act8
     */
    public act8() {
        initComponents();
        ompleInfo();
        ompleTable();
        jTable1.setEnabled(false);
        jTextPuntos.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSortir = new javax.swing.JButton();
        jReiniciar = new javax.swing.JButton();
        jTextPuntos = new javax.swing.JTextField();
        jpuntoslabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jrecordpuntos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"?", "?", "?", "?"},
                {"?", "?", "?", "?"},
                {"?", "?", "?", "?"},
                {"?", "?", "?", "?"}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jTable1.setRowHeight(50);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jSortir.setText("Sortir");
        jSortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSortirActionPerformed(evt);
            }
        });

        jReiniciar.setText("Començar");
        jReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReiniciarActionPerformed(evt);
            }
        });

        jTextPuntos.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jTextPuntos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jpuntoslabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jpuntoslabel.setText("Punts :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Rècord :");

        jrecordpuntos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jrecordpuntos.setText("0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("punts");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpuntoslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jrecordpuntos)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jSortir)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jReiniciar))
                        .addComponent(jTextPuntos, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jrecordpuntos)
                            .addComponent(jLabel2))
                        .addGap(25, 25, 25)
                        .addComponent(jpuntoslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSortir)
                            .addComponent(jReiniciar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSortirActionPerformed
        JOptionPane.showConfirmDialog(null,
                "Has hecho " + contador + " puntos",
                "El nuevo juego del año",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.PLAIN_MESSAGE);
        dispose();
    }//GEN-LAST:event_jSortirActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = filaClicada();
        int columna = columnaClicada();
        
        if(jTable1.getValueAt(fila, columna) == "?") {
            jTable1.setValueAt(cuadrados[fila][columna], fila, columna);
            if("0".equals(cuadrados[fila][columna])) {
                contador++;
            } else if ("W".equals(cuadrados[fila][columna])) {
                if (contador != 0) {
                    contador = contador * 2;
                }
            } else {
                if(Integer.valueOf(jrecordpuntos.getText()) < contador) {
                    jrecordpuntos.setText(String.valueOf(contador));
                }
                JOptionPane.showConfirmDialog(null,
                "Has hecho " + contador + " puntos",
                "El nuevo juego del año",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.PLAIN_MESSAGE);
                jTable1.setEnabled(false);
            }
        }
        jTextPuntos.setText(String.valueOf(contador));
        System.out.println(contador);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReiniciarActionPerformed
        if(jReiniciar.getText().equalsIgnoreCase("començar")) {
            jTable1.setEnabled(true);
            jTextPuntos.setText(String.valueOf(0));
            jReiniciar.setText("Reinicia Partida");
        } else {
            if(Integer.valueOf(jrecordpuntos.getText()) < contador) {
                jrecordpuntos.setText(String.valueOf(contador));
            }
            jTable1.setEnabled(false);
            jReiniciar.setText("Començar");
            contador = 0;
            contadorW = 0;
            contadorX = 0;
            ompleInfo();
            ompleTable();
        }
    }//GEN-LAST:event_jReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(act8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(act8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(act8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(act8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new act8().setVisible(true);
            }
        });
    }
    
    private void ompleInfo() {
        Random rand = new Random();         
        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 4; j++) {
                int rand_int1 = rand.nextInt(3); //0 o 1
                if (rand_int1 == 0) {
                    cuadrados[i][j] = "0";
                } else if (rand_int1 == 1){
                    if (contadorW != 3) {
                        cuadrados[i][j] = "W";
                        contadorW++;
                    } else {
                        cuadrados[i][j] = "0";
                    }
                } else {
                    if (contadorX != 2) {
                        cuadrados[i][j] = "X";
                        contadorX++;
                    } else {
                        cuadrados[i][j] = "0";
                    }
                }
            }
        }
    }
    
    public void ompleTable(){
        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 4; j++) {
                jTable1.setValueAt("?", i, j);
            }
        }
    }
    
     private int columnaClicada() {
       return jTable1.getSelectedColumn();
    }
    
    private int filaClicada() {
        return jTable1.getSelectedRow();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jReiniciar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSortir;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextPuntos;
    private javax.swing.JLabel jpuntoslabel;
    private javax.swing.JLabel jrecordpuntos;
    // End of variables declaration//GEN-END:variables
    
}


