package uf2m6;
// Generated 08/06/2021 17:31:23 by Hibernate Tools 4.3.1



/**
 * Usuaris generated by hbm2java
 */
public class Usuaris  implements java.io.Serializable {


     private String usuari;
     private String contrasenya;
     private String pregunta;
     private String resposta;

    public Usuaris() {
    }

    public Usuaris(String usuari, String contrasenya, String pregunta, String resposta) {
       this.usuari = usuari;
       this.contrasenya = contrasenya;
       this.pregunta = pregunta;
       this.resposta = resposta;
    }
   
    public String getUsuari() {
        return this.usuari;
    }
    
    public void setUsuari(String usuari) {
        this.usuari = usuari;
    }
    public String getContrasenya() {
        return this.contrasenya;
    }
    
    public void setContrasenya(String contrasenya) {
        this.contrasenya = contrasenya;
    }
    public String getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(String pregunta) {
        this.pregunta = pregunta;
    }
    public String getResposta() {
        return this.resposta;
    }
    
    public void setResposta(String resposta) {
        this.resposta = resposta;
    }




}


