package entity;
// Generated 28-ene-2021 22:26:54 by Hibernate Tools 4.3.1



/**
 * Movimiento generated by hbm2java
 */
public class Movimiento  implements java.io.Serializable {


     private Integer idMoviment;
     private Partida partida;
     private int columnaOrigen;
     private int columnaDesti;
     private int filaOrigen;
     private int filaDesti;

    public Movimiento() {
    }

    public Movimiento(Partida partida, int columnaOrigen, int columnaDesti, int filaOrigen, int filaDesti) {
       this.partida = partida;
       this.columnaOrigen = columnaOrigen;
       this.columnaDesti = columnaDesti;
       this.filaOrigen = filaOrigen;
       this.filaDesti = filaDesti;
    }
   
    public Integer getIdMoviment() {
        return this.idMoviment;
    }
    
    public void setIdMoviment(Integer idMoviment) {
        this.idMoviment = idMoviment;
    }
    public Partida getPartida() {
        return this.partida;
    }
    
    public void setPartida(Partida partida) {
        this.partida = partida;
    }
    public int getColumnaOrigen() {
        return this.columnaOrigen;
    }
    
    public void setColumnaOrigen(int columnaOrigen) {
        this.columnaOrigen = columnaOrigen;
    }
    public int getColumnaDesti() {
        return this.columnaDesti;
    }
    
    public void setColumnaDesti(int columnaDesti) {
        this.columnaDesti = columnaDesti;
    }
    public int getFilaOrigen() {
        return this.filaOrigen;
    }
    
    public void setFilaOrigen(int filaOrigen) {
        this.filaOrigen = filaOrigen;
    }
    public int getFilaDesti() {
        return this.filaDesti;
    }
    
    public void setFilaDesti(int filaDesti) {
        this.filaDesti = filaDesti;
    }




}


